-- LIBRO - CORRECTED SCHEMA

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- PROFILES TABLE (Linked to Supabase Auth)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  email TEXT,
  role TEXT DEFAULT 'admin', -- admin, librarian, staff
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- LIBRARY MEMBERSHIP PLANS TABLE (Renamed from membership_plans)
CREATE TABLE public.library_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, -- e.g., "Daily Reading", "Monthly Reading", "Student Plan"
  duration_months INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT,
  seat_access BOOLEAN DEFAULT true, -- Can use reading room seats
  book_limit INTEGER DEFAULT 0, -- Max books that can be borrowed (0 = reading room only)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- MEMBERS TABLE (Library Members)
CREATE TABLE public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  birth_date DATE,
  city TEXT,
  address TEXT,
  seat_no TEXT UNIQUE, -- Reading room seat number
  library_card_no TEXT UNIQUE, -- Library card ID
  status TEXT DEFAULT 'active', -- active, suspended, expired
  plan_id BIGINT REFERENCES public.library_plans(id),
  join_date DATE,
  end_date DATE,
  id_document_type TEXT, -- Aadhaar, PAN, Voter ID, etc.
  id_number TEXT,
  photo_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- BOOKS TABLE (Optional - if you manage books)
CREATE TABLE public.books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  isbn TEXT UNIQUE,
  category TEXT,
  total_copies INTEGER DEFAULT 1,
  available_copies INTEGER DEFAULT 1,
  shelf_location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- BOOK ISSUES TABLE (Optional - if members can borrow books)
CREATE TABLE public.book_issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES public.books(id),
  member_id BIGINT REFERENCES public.members(id),
  issue_date DATE DEFAULT CURRENT_DATE,
  due_date DATE,
  return_date DATE,
  status TEXT DEFAULT 'issued', -- issued, returned, overdue
  fine_amount DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- SETTINGS TABLE
CREATE TABLE public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB,
  description TEXT
);

-- ATTENDANCE TABLE (Library visits)
CREATE TABLE public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES public.members(id),
  check_in TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  check_out TIMESTAMP WITH TIME ZONE,
  source TEXT DEFAULT 'manual', -- manual, biometric
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- PAYMENTS TABLE (Membership fees, fines, etc.)
CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES public.members(id),
  amount DECIMAL(10,2) NOT NULL,
  payment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  payment_method TEXT, -- cash, upi, card, etc.
  transaction_id TEXT,
  type TEXT, -- membership, late_fee, damage_fee, other
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- EXPENDITURES TABLE (Library operational costs)
CREATE TABLE public.expenditures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  category TEXT, -- books, electricity, rent, salaries, maintenance, etc.
  date DATE DEFAULT CURRENT_DATE,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- RLS POLICIES (Basic Security)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenditures ENABLE ROW LEVEL SECURITY;

-- Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- For other tables, allowing full access to authenticated users (Admin/Staff)
CREATE POLICY "Enable all for authenticated" ON public.members FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON public.library_plans FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON public.books FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON public.book_issues FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON public.settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON public.attendance FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON public.payments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated" ON public.expenditures FOR ALL USING (auth.role() = 'authenticated');

-- FUNCTIONS & TRIGGERS
-- Handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, email, role, avatar_url)
  VALUES (
    NEW.id, 
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'full_name',
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'role', 'admin'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Insert sample library plans
INSERT INTO public.library_plans (name, duration_months, price, description, seat_access, book_limit) VALUES
  ('Daily Reading', 0, 20.00, 'Daily reading room access only', true, 0),
  ('Monthly Reading', 1, 500.00, 'Monthly reading room access', true, 0),
  ('Student Monthly', 1, 300.00, 'Student discount - Monthly reading room', true, 0),
  ('Annual Reading', 12, 5000.00, 'Annual reading room access', true, 0),
  ('Book Borrower Monthly', 1, 800.00, 'Monthly reading room + 3 books borrowing', true, 3),
  ('Premium Annual', 12, 8000.00, 'Annual reading room + 5 books borrowing', true, 5);
