-- COMPATIBILITY MIGRATION SCRIPT
-- This script adds missing tables and creates views for compatibility with desktop app

-- Create the missing membership_plans table (as a view or actual table)
-- This ensures compatibility with desktop app that expects 'membership_plans'
DO $$
BEGIN
    -- Check if membership_plans table/view exists
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'membership_plans' AND table_schema = 'public'
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.views 
        WHERE table_name = 'membership_plans' AND table_schema = 'public'
    ) THEN
        -- Create a view that maps library_plans to membership_plans
        -- This provides backward compatibility
        CREATE VIEW public.membership_plans AS 
        SELECT 
            id,
            name,
            duration_months * 30 as duration_days, -- Convert months to days  
            price,
            description,
            created_at,
            COALESCE(seat_access, true) as is_active
        FROM public.library_plans;
        
        RAISE NOTICE 'Created membership_plans view for compatibility';
    END IF;
END $$;

-- Create missing users table for internal authentication compatibility
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'receptionist' CHECK (role IN ('admin', 'receptionist')),
    full_name TEXT,
    email TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_login TIMESTAMP WITH TIME ZONE
);

-- Create password_change_otps table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.password_change_otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    otp TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure members table has all required columns for desktop app compatibility
DO $$
BEGIN
    -- Add missing columns to members table
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'members' AND column_name = 'qr_code' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.members ADD COLUMN qr_code TEXT;
        RAISE NOTICE 'Added qr_code column to members table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'members' AND column_name = 'fingerprint_template' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.members ADD COLUMN fingerprint_template BYTEA;
        RAISE NOTICE 'Added fingerprint_template column to members table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'members' AND column_name = 'updated_at' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.members ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
        RAISE NOTICE 'Added updated_at column to members table';
    END IF;
END $$;

-- Ensure payments table has all required columns  
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'payments' AND column_name = 'mode' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.payments ADD COLUMN mode TEXT DEFAULT 'cash' CHECK (mode IN ('cash', 'card', 'upi', 'bank_transfer'));
        RAISE NOTICE 'Added mode column to payments table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'payments' AND column_name = 'plan_id' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.payments ADD COLUMN plan_id BIGINT REFERENCES public.library_plans(id);
        RAISE NOTICE 'Added plan_id column to payments table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'payments' AND column_name = 'note' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.payments ADD COLUMN note TEXT;
        RAISE NOTICE 'Added note column to payments table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'payments' AND column_name = 'receipt_number' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.payments ADD COLUMN receipt_number TEXT;
        RAISE NOTICE 'Added receipt_number column to payments table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'payments' AND column_name = 'paid_at' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.payments ADD COLUMN paid_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
        RAISE NOTICE 'Added paid_at column to payments table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'payments' AND column_name = 'created_by' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.payments ADD COLUMN created_by UUID REFERENCES public.profiles(id);
        RAISE NOTICE 'Added created_by column to payments table';
    END IF;
END $$;

-- Ensure attendance table has all required columns
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'attendance' AND column_name = 'source' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.attendance ADD COLUMN source TEXT DEFAULT 'manual' CHECK (source IN ('biometric', 'manual', 'card', 'qr'));
        RAISE NOTICE 'Added source column to attendance table';
    END IF;
END $$;

-- Ensure expenditures table has all required columns
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'expenditures' AND column_name = 'description' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.expenditures ADD COLUMN description TEXT NOT NULL DEFAULT 'Expense';
        RAISE NOTICE 'Added description column to expenditures table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'expenditures' AND column_name = 'category' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.expenditures ADD COLUMN category TEXT NOT NULL DEFAULT 'Other';
        RAISE NOTICE 'Added category column to expenditures table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'expenditures' AND column_name = 'payment_mode' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.expenditures ADD COLUMN payment_mode TEXT DEFAULT 'cash' CHECK (payment_mode IN ('cash', 'card', 'upi', 'bank_transfer', 'cheque'));
        RAISE NOTICE 'Added payment_mode column to expenditures table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'expenditures' AND column_name = 'receipt_number' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.expenditures ADD COLUMN receipt_number TEXT;
        RAISE NOTICE 'Added receipt_number column to expenditures table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'expenditures' AND column_name = 'notes' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.expenditures ADD COLUMN notes TEXT;
        RAISE NOTICE 'Added notes column to expenditures table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'expenditures' AND column_name = 'updated_at' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.expenditures ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
        RAISE NOTICE 'Added updated_at column to expenditures table';
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'expenditures' AND column_name = 'created_by' AND table_schema = 'public'
    ) THEN
        ALTER TABLE public.expenditures ADD COLUMN created_by UUID REFERENCES public.profiles(id);
        RAISE NOTICE 'Added created_by column to expenditures table';
    END IF;
END $$;

-- Enable RLS on new tables
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_change_otps ENABLE ROW LEVEL SECURITY;

-- Create policies for new tables
CREATE POLICY "Enable all access for authenticated users" ON public.users FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all access for authenticated users" ON public.password_change_otps FOR ALL USING (auth.role() = 'authenticated');

-- Insert default admin user (password: admin123)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.users WHERE username = 'admin') THEN
        INSERT INTO public.users (username, password_hash, role, full_name, email) 
        VALUES (
            'admin', 
            '$2a$10$8K1p/a0dUrziV2qNlUgUyOZyUUmrGdDj8Xx.3DF1/RXrmg3HA1M1i', -- bcrypt hash for 'admin123'
            'admin', 
            'System Administrator', 
            'admin@library.local'
        );
        RAISE NOTICE 'Created default admin user (username: admin, password: admin123)';
    END IF;
END $$;

-- Insert default library plans if library_plans table is empty
DO $$
DECLARE
    plan_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO plan_count FROM public.library_plans;
    
    IF plan_count = 0 THEN
        INSERT INTO public.library_plans (name, duration_months, price, description, seat_access, book_limit) VALUES
            (1, 'Daily', 50.00, 'Daily access', true, 0),
            (7, 'Weekly', 300.00, 'Weekly access', true, 0),
            (30, 'Monthly', 1000.00, 'Monthly access', true, 0),
            (90, 'Quarterly', 2700.00, 'Quarterly access', true, 0),
            (180, 'Half Yearly', 5000.00, 'Half yearly access', true, 0),
            (365, 'Annual', 9000.00, 'Annual access', true, 0),
            (30, 'Student Monthly', 600.00, 'Student monthly plan', true, 0),
            (365, 'Student Annual', 6000.00, 'Student annual plan', true, 0);
            
        RAISE NOTICE 'Inserted default library plans';
    END IF;
END $$;

-- Insert default settings if settings table is empty
DO $$
DECLARE
    settings_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO settings_count FROM public.settings;
    
    IF settings_count = 0 THEN
        INSERT INTO public.settings (key, value, description) VALUES
            ('library_name', 'Study Room Library', 'Name of the library'),
            ('library_address', 'Main Street, City', 'Library address'),
            ('library_phone', '+1234567890', 'Library contact number'),
            ('notification_days', '10', 'Days before expiry to send notifications'),
            ('auto_backup', '1', 'Enable automatic database backup'),
            ('seat_capacity', '50', 'Total reading room capacity'),
            ('operating_hours', '6:00-22:00', 'Library operating hours'),
            ('late_fee_per_day', '5.00', 'Late fee charges per day'),
            ('deposit_amount', '200.00', 'Security deposit amount');
            
        RAISE NOTICE 'Inserted default settings';
    END IF;
END $$;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_members_phone ON public.members(phone);
CREATE INDEX IF NOT EXISTS idx_members_email ON public.members(email);
CREATE INDEX IF NOT EXISTS idx_members_status ON public.members(status);
CREATE INDEX IF NOT EXISTS idx_members_plan_id ON public.members(plan_id);
CREATE INDEX IF NOT EXISTS idx_members_end_date ON public.members(end_date);

CREATE INDEX IF NOT EXISTS idx_payments_member_id ON public.payments(member_id);
CREATE INDEX IF NOT EXISTS idx_payments_paid_at ON public.payments(paid_at);

CREATE INDEX IF NOT EXISTS idx_attendance_member_id ON public.attendance(member_id);
CREATE INDEX IF NOT EXISTS idx_attendance_check_in ON public.attendance(check_in);

CREATE INDEX IF NOT EXISTS idx_notifications_member_id ON public.notifications(member_id);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON public.notifications(status);

-- Update timestamp trigger function
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add update triggers for tables with updated_at columns
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.triggers WHERE trigger_name = 'handle_updated_at_members') THEN
        CREATE TRIGGER handle_updated_at_members 
            BEFORE UPDATE ON public.members 
            FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.triggers WHERE trigger_name = 'handle_updated_at_expenditures') THEN
        CREATE TRIGGER handle_updated_at_expenditures 
            BEFORE UPDATE ON public.expenditures 
            FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
    END IF;
END $$;

SELECT 'Database migration completed! Schema now matches desktop app structure.' as status;
