-- READING ROOM LIBRARY MANAGEMENT SYSTEM - COMPLETE SCHEMA
-- Aligned with desktop version for web application

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ===========================
-- USER MANAGEMENT TABLES
-- ===========================

-- PROFILES TABLE (Linked to Supabase Auth - replaces users table)
-- Handles owner, receptionist, and admin roles
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  full_name TEXT,
  email TEXT,
  role TEXT DEFAULT 'receptionist' CHECK(role IN ('admin', 'owner', 'receptionist', 'staff')),
  avatar_url TEXT,
  is_active BOOLEAN DEFAULT true,
  last_login TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PASSWORD CHANGE OTPs TABLE (for password recovery)
CREATE TABLE IF NOT EXISTS public.password_change_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  otp TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ===========================
-- LIBRARY SETTINGS & CONFIGURATION
-- ===========================

-- SETTINGS TABLE (Library configuration)
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  description TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ===========================
-- MEMBERSHIP MANAGEMENT
-- ===========================

-- MEMBERSHIP PLANS TABLE (renamed from library_plans to match desktop version)
CREATE TABLE IF NOT EXISTS public.membership_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  duration_days INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- MEMBERS TABLE (Reading room members)
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  birth_date DATE,
  city TEXT,
  address TEXT,
  id_document_type TEXT, -- Aadhaar, PAN, Voter ID, Driving License, etc.
  id_number TEXT,
  seat_no TEXT UNIQUE, -- Reading room seat number
  library_card_no TEXT UNIQUE, -- Library card ID (for QR code/barcode)
  plan_id BIGINT REFERENCES public.membership_plans(id),
  join_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status TEXT DEFAULT 'active' CHECK(status IN ('active', 'expired', 'suspended')),
  photo_url TEXT,
  fingerprint_template TEXT, -- For biometric integration
  qr_code TEXT, -- QR code data
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ===========================
-- FINANCIAL MANAGEMENT
-- ===========================

-- PAYMENTS TABLE (Membership fees, renewals, etc.)
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL,
  amount DECIMAL(10,2) NOT NULL,
  mode TEXT DEFAULT 'cash' CHECK(mode IN ('cash', 'card', 'upi', 'bank_transfer')),
  plan_id BIGINT REFERENCES public.membership_plans(id),
  note TEXT,
  receipt_number TEXT,
  payment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- EXPENDITURES TABLE (Library operational costs)
CREATE TABLE IF NOT EXISTS public.expenditures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  category TEXT NOT NULL, -- electricity, rent, salaries, maintenance, furniture, stationery, etc.
  amount DECIMAL(10,2) NOT NULL,
  payment_mode TEXT DEFAULT 'cash' CHECK(payment_mode IN ('cash', 'card', 'upi', 'bank_transfer', 'cheque')),
  date DATE NOT NULL,
  receipt_number TEXT,
  notes TEXT,
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ===========================
-- ATTENDANCE & NOTIFICATIONS
-- ===========================

-- ATTENDANCE TABLE (Reading room visits)
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE NOT NULL,
  check_in TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  check_out TIMESTAMP WITH TIME ZONE,
  source TEXT DEFAULT 'manual' CHECK(source IN ('biometric', 'manual', 'card', 'qr')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- NOTIFICATIONS TABLE (Track sent notifications - email/WhatsApp/SMS)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('email', 'whatsapp', 'sms')),
  subject TEXT,
  message TEXT,
  status TEXT DEFAULT 'pending' CHECK(status IN ('pending', 'sent', 'failed')),
  sent_at TIMESTAMP WITH TIME ZONE,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- ===========================
-- INDEXES FOR PERFORMANCE
-- ===========================

CREATE INDEX IF NOT EXISTS idx_members_status ON public.members(status);
CREATE INDEX IF NOT EXISTS idx_members_end_date ON public.members(end_date);
CREATE INDEX IF NOT EXISTS idx_members_seat_no ON public.members(seat_no);
CREATE INDEX IF NOT EXISTS idx_payments_member_id ON public.payments(member_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON public.payments(payment_date);
CREATE INDEX IF NOT EXISTS idx_attendance_member_id ON public.attendance(member_id);
CREATE INDEX IF NOT EXISTS idx_attendance_check_in ON public.attendance(check_in);
CREATE INDEX IF NOT EXISTS idx_expenditures_date ON public.expenditures(date);
CREATE INDEX IF NOT EXISTS idx_notifications_member_id ON public.notifications(member_id);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON public.notifications(status);

-- ===========================
-- ROW LEVEL SECURITY (RLS)
-- ===========================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenditures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_change_otps ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.members;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.membership_plans;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.library_plans;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.books;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.book_issues;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.settings;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.attendance;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.payments;
DROP POLICY IF EXISTS "Enable all for authenticated" ON public.expenditures;

-- Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- For other tables, allowing full access to authenticated users
CREATE POLICY "Enable all for authenticated users" ON public.members FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON public.membership_plans FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON public.settings FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON public.attendance FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON public.payments FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON public.expenditures FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON public.notifications FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Enable all for authenticated users" ON public.password_change_otps FOR ALL USING (auth.role() = 'authenticated');

-- ===========================
-- FUNCTIONS & TRIGGERS
-- ===========================

-- Handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, email, role, avatar_url)
  VALUES (
    NEW.id, 
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'full_name',
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'role', 'receptionist'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger if it doesn't exist
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers for updated_at
DROP TRIGGER IF EXISTS update_profiles_updated_at ON public.profiles;
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_members_updated_at ON public.members;
CREATE TRIGGER update_members_updated_at BEFORE UPDATE ON public.members
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_expenditures_updated_at ON public.expenditures;
CREATE TRIGGER update_expenditures_updated_at BEFORE UPDATE ON public.expenditures
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_settings_updated_at ON public.settings;
CREATE TRIGGER update_settings_updated_at BEFORE UPDATE ON public.settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ===========================
-- DEFAULT DATA
-- ===========================

-- Insert default membership plans
INSERT INTO public.membership_plans (name, duration_days, price, description) 
VALUES
  ('Daily Reading', 1, 20.00, 'Single day reading room access'),
  ('Weekly Reading', 7, 120.00, 'One week reading room access'),
  ('Monthly Reading', 30, 500.00, 'Monthly reading room access'),
  ('Student Monthly', 30, 300.00, 'Student discount - Monthly reading room'),
  ('Quarterly Reading', 90, 1350.00, '3 months reading room access'),
  ('Half Yearly', 180, 2500.00, '6 months reading room access'),
  ('Annual Reading', 365, 5000.00, 'Annual reading room access')
ON CONFLICT DO NOTHING;

-- Insert default settings (for first-time setup)
INSERT INTO public.settings (key, value, description) VALUES
  ('library_name', '""', 'Name of the library/reading room'),
  ('library_address', '""', 'Library full address'),
  ('library_city', '""', 'City'),
  ('library_state', '""', 'State'),
  ('library_pincode', '""', 'PIN code'),
  ('library_phone', '""', 'Library contact number'),
  ('library_email', '""', 'Library email address'),
  ('library_owner_name', '""', 'Owner/Manager name'),
  ('total_seats', '"0"', 'Total number of seats available in reading room'),
  ('notification_days', '"10"', 'Days before expiry to send notifications'),
  ('auto_backup', '"false"', 'Enable automatic database backup'),
  ('receipt_prefix', '"RR"', 'Prefix for receipt numbers'),
  ('late_fee_per_day', '"10"', 'Late fee amount per day'),
  ('setup_completed', '"false"', 'Whether initial setup is completed'),
  ('business_hours', '{"open": "06:00", "close": "22:00"}', 'Library opening and closing hours'),
  ('gst_number', '""', 'GST number if applicable'),
  ('enable_biometric', '"false"', 'Enable biometric attendance'),
  ('enable_notifications', '"false"', 'Enable email/SMS notifications')
ON CONFLICT (key) DO NOTHING;

-- ===========================
-- CLEANUP OLD TABLES
-- ===========================

-- Drop book-related tables if they exist (this is a reading room, not a lending library)
DROP TABLE IF EXISTS public.book_issues CASCADE;
DROP TABLE IF EXISTS public.books CASCADE;

-- Rename library_plans to membership_plans if it exists
DO $$ 
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'library_plans') 
     AND NOT EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'membership_plans') THEN
    -- First, drop the foreign key constraints
    ALTER TABLE IF EXISTS public.members DROP CONSTRAINT IF EXISTS members_plan_id_fkey;
    ALTER TABLE IF EXISTS public.payments DROP CONSTRAINT IF EXISTS payments_plan_id_fkey;
    
    -- Rename the table
    ALTER TABLE public.library_plans RENAME TO membership_plans;
    
    -- Recreate the foreign key constraints
    ALTER TABLE public.members ADD CONSTRAINT members_plan_id_fkey 
      FOREIGN KEY (plan_id) REFERENCES public.membership_plans(id);
    ALTER TABLE public.payments ADD CONSTRAINT payments_plan_id_fkey 
      FOREIGN KEY (plan_id) REFERENCES public.membership_plans(id);
  ELSIF EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'library_plans') 
        AND EXISTS (SELECT FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'membership_plans') THEN
    -- Both tables exist, drop the old library_plans table
    DROP TABLE IF EXISTS public.library_plans CASCADE;
  END IF;
END $$;

-- Add missing columns to members table if they don't exist
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'fingerprint_template') THEN
    ALTER TABLE public.members ADD COLUMN fingerprint_template TEXT;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'qr_code') THEN
    ALTER TABLE public.members ADD COLUMN qr_code TEXT;
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'members' AND column_name = 'library_card_no') THEN
    ALTER TABLE public.members ADD COLUMN library_card_no TEXT UNIQUE;
  END IF;
END $$;
