-- LIBRARY MANAGEMENT SYSTEM - SAFE SCHEMA SETUP
-- This script handles existing tables and creates missing ones safely

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- First, let's check what exists and what type the members.id is
DO $$
DECLARE
    members_exists BOOLEAN := FALSE;
    members_id_type TEXT := 'bigint';
BEGIN
    -- Check if members table exists and get its id column type
    SELECT EXISTS (
        SELECT 1 FROM information_schema.tables 
        WHERE table_name = 'members' AND table_schema = 'public'
    ) INTO members_exists;
    
    IF members_exists THEN
        SELECT data_type INTO members_id_type
        FROM information_schema.columns 
        WHERE table_name = 'members' AND column_name = 'id' AND table_schema = 'public';
        
        RAISE NOTICE 'Members table exists with id type: %', members_id_type;
    ELSE
        RAISE NOTICE 'Members table does not exist, will create with BIGINT id';
    END IF;
END $$;

-- Drop existing problematic foreign key constraints
DO $$
BEGIN
    -- Drop foreign key constraints that might have type mismatches
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'book_issues_member_id_fkey') THEN
        ALTER TABLE public.book_issues DROP CONSTRAINT book_issues_member_id_fkey;
        RAISE NOTICE 'Dropped book_issues_member_id_fkey constraint';
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'attendance_member_id_fkey') THEN
        ALTER TABLE public.attendance DROP CONSTRAINT attendance_member_id_fkey;
        RAISE NOTICE 'Dropped attendance_member_id_fkey constraint';
    END IF;
    
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'payments_member_id_fkey') THEN
        ALTER TABLE public.payments DROP CONSTRAINT payments_member_id_fkey;
        RAISE NOTICE 'Dropped payments_member_id_fkey constraint';
    END IF;
END $$;

-- Create PROFILES table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  email TEXT,
  role TEXT DEFAULT 'admin',
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create LIBRARY_PLANS table
CREATE TABLE IF NOT EXISTS public.library_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  duration_months INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description TEXT,
  seat_access BOOLEAN DEFAULT true,
  book_limit INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create MEMBERS table if it doesn't exist, or ensure it has all required columns
DO $$
BEGIN
    -- Create members table if it doesn't exist
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'members' AND table_schema = 'public') THEN
        CREATE TABLE public.members (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          email TEXT,
          phone TEXT,
          birth_date DATE,
          city TEXT,
          address TEXT,
          seat_no TEXT UNIQUE,
          library_card_no TEXT UNIQUE,
          status TEXT DEFAULT 'active',
          plan_id BIGINT REFERENCES public.library_plans(id),
          join_date DATE,
          end_date DATE,
          id_document_type TEXT,
          id_number TEXT,
          photo_url TEXT,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
        );
        RAISE NOTICE 'Created members table with BIGINT id';
    ELSE
        -- Add missing columns to existing members table
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='plan_id') THEN
            ALTER TABLE public.members ADD COLUMN plan_id BIGINT;
            RAISE NOTICE 'Added plan_id column to members';
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='library_card_no') THEN
            ALTER TABLE public.members ADD COLUMN library_card_no TEXT UNIQUE;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='id_document_type') THEN
            ALTER TABLE public.members ADD COLUMN id_document_type TEXT;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='id_number') THEN
            ALTER TABLE public.members ADD COLUMN id_number TEXT;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='photo_url') THEN
            ALTER TABLE public.members ADD COLUMN photo_url TEXT;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='birth_date') THEN
            ALTER TABLE public.members ADD COLUMN birth_date DATE;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='city') THEN
            ALTER TABLE public.members ADD COLUMN city TEXT;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='address') THEN
            ALTER TABLE public.members ADD COLUMN address TEXT;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='seat_no') THEN
            ALTER TABLE public.members ADD COLUMN seat_no TEXT UNIQUE;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='join_date') THEN
            ALTER TABLE public.members ADD COLUMN join_date DATE;
        END IF;
        
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='members' AND column_name='end_date') THEN
            ALTER TABLE public.members ADD COLUMN end_date DATE;
        END IF;
    END IF;
END $$;

-- Add foreign key constraint for plan_id after both tables exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE constraint_name = 'members_plan_id_fkey' AND table_name = 'members'
    ) THEN
        ALTER TABLE public.members ADD CONSTRAINT members_plan_id_fkey 
        FOREIGN KEY (plan_id) REFERENCES public.library_plans(id);
        RAISE NOTICE 'Added foreign key constraint members_plan_id_fkey';
    END IF;
END $$;

-- Create other tables
CREATE TABLE IF NOT EXISTS public.books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  isbn TEXT UNIQUE,
  category TEXT,
  total_copies INTEGER DEFAULT 1,
  available_copies INTEGER DEFAULT 1,
  shelf_location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create tables with proper member_id type based on members table
DO $$
DECLARE
    members_id_type TEXT;
BEGIN
    -- Get the actual data type of members.id
    SELECT data_type INTO members_id_type
    FROM information_schema.columns 
    WHERE table_name = 'members' AND column_name = 'id' AND table_schema = 'public';
    
    -- Create book_issues table
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'book_issues' AND table_schema = 'public') THEN
        IF members_id_type = 'uuid' THEN
            EXECUTE 'CREATE TABLE public.book_issues (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              book_id BIGINT REFERENCES public.books(id),
              member_id UUID,
              issue_date DATE DEFAULT CURRENT_DATE,
              due_date DATE,
              return_date DATE,
              status TEXT DEFAULT ''issued'',
              fine_amount DECIMAL(10,2) DEFAULT 0,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
            )';
        ELSE
            EXECUTE 'CREATE TABLE public.book_issues (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              book_id BIGINT REFERENCES public.books(id),
              member_id BIGINT,
              issue_date DATE DEFAULT CURRENT_DATE,
              due_date DATE,
              return_date DATE,
              status TEXT DEFAULT ''issued'',
              fine_amount DECIMAL(10,2) DEFAULT 0,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
            )';
        END IF;
        RAISE NOTICE 'Created book_issues table with member_id type: %', members_id_type;
    END IF;
    
    -- Create attendance table
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'attendance' AND table_schema = 'public') THEN
        IF members_id_type = 'uuid' THEN
            EXECUTE 'CREATE TABLE public.attendance (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              member_id UUID,
              check_in TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
              check_out TIMESTAMP WITH TIME ZONE,
              source TEXT DEFAULT ''manual'',
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
            )';
        ELSE
            EXECUTE 'CREATE TABLE public.attendance (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              member_id BIGINT,
              check_in TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
              check_out TIMESTAMP WITH TIME ZONE,
              source TEXT DEFAULT ''manual'',
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
            )';
        END IF;
        RAISE NOTICE 'Created attendance table with member_id type: %', members_id_type;
    END IF;
    
    -- Create payments table
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'payments' AND table_schema = 'public') THEN
        IF members_id_type = 'uuid' THEN
            EXECUTE 'CREATE TABLE public.payments (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              member_id UUID,
              amount DECIMAL(10,2) NOT NULL,
              payment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
              payment_method TEXT,
              transaction_id TEXT,
              type TEXT,
              notes TEXT,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
            )';
        ELSE
            EXECUTE 'CREATE TABLE public.payments (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              member_id BIGINT,
              amount DECIMAL(10,2) NOT NULL,
              payment_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
              payment_method TEXT,
              transaction_id TEXT,
              type TEXT,
              notes TEXT,
              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
            )';
        END IF;
        RAISE NOTICE 'Created payments table with member_id type: %', members_id_type;
    END IF;
END $$;

-- Add foreign key constraints after tables are created
DO $$
DECLARE
    members_id_type TEXT;
BEGIN
    SELECT data_type INTO members_id_type
    FROM information_schema.columns 
    WHERE table_name = 'members' AND column_name = 'id' AND table_schema = 'public';
    
    -- Add foreign key constraints
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'book_issues_member_id_fkey') THEN
        ALTER TABLE public.book_issues ADD CONSTRAINT book_issues_member_id_fkey 
        FOREIGN KEY (member_id) REFERENCES public.members(id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'attendance_member_id_fkey') THEN
        ALTER TABLE public.attendance ADD CONSTRAINT attendance_member_id_fkey 
        FOREIGN KEY (member_id) REFERENCES public.members(id);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'payments_member_id_fkey') THEN
        ALTER TABLE public.payments ADD CONSTRAINT payments_member_id_fkey 
        FOREIGN KEY (member_id) REFERENCES public.members(id);
    END IF;
    
    RAISE NOTICE 'Added foreign key constraints for member_id type: %', members_id_type;
END $$;

-- Create remaining tables
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value JSONB,
  description TEXT
);

CREATE TABLE IF NOT EXISTS public.expenditures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  category TEXT,
  date DATE DEFAULT CURRENT_DATE,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.library_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenditures ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;

-- Create policies for profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Create permissive policies for all other tables (allow all for authenticated users)
DO $$
DECLARE
    table_names TEXT[] := ARRAY['members', 'library_plans', 'books', 'book_issues', 'settings', 'attendance', 'payments', 'expenditures'];
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY table_names LOOP
        -- Drop existing policies
        EXECUTE format('DROP POLICY IF EXISTS "Enable read access for authenticated users" ON public.%I', table_name);
        EXECUTE format('DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON public.%I', table_name);
        EXECUTE format('DROP POLICY IF EXISTS "Enable update access for authenticated users" ON public.%I', table_name);
        EXECUTE format('DROP POLICY IF EXISTS "Enable delete access for authenticated users" ON public.%I', table_name);
        
        -- Create new policies
        EXECUTE format('CREATE POLICY "Enable read access for authenticated users" ON public.%I FOR SELECT USING (auth.role() = ''authenticated'')', table_name);
        EXECUTE format('CREATE POLICY "Enable insert access for authenticated users" ON public.%I FOR INSERT WITH CHECK (auth.role() = ''authenticated'')', table_name);
        EXECUTE format('CREATE POLICY "Enable update access for authenticated users" ON public.%I FOR UPDATE USING (auth.role() = ''authenticated'')', table_name);
        EXECUTE format('CREATE POLICY "Enable delete access for authenticated users" ON public.%I FOR DELETE USING (auth.role() = ''authenticated'')', table_name);
    END LOOP;
END $$;

-- Create trigger function and trigger
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, email, role, avatar_url)
  VALUES (
    NEW.id, 
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'full_name',
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'role', 'admin'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Insert sample library plans
INSERT INTO public.library_plans (name, duration_months, price, description, seat_access, book_limit) 
SELECT * FROM (VALUES
  ('Daily Reading', 0, 20.00, 'Daily reading room access only', true, 0),
  ('Monthly Reading', 1, 500.00, 'Monthly reading room access', true, 0),
  ('Student Monthly', 1, 300.00, 'Student discount - Monthly reading room', true, 0),
  ('Annual Reading', 12, 5000.00, 'Annual reading room access', true, 0),
  ('Book Borrower Monthly', 1, 800.00, 'Monthly reading room + 3 books borrowing', true, 3),
  ('Premium Annual', 12, 8000.00, 'Annual reading room + 5 books borrowing', true, 5)
) AS v(name, duration_months, price, description, seat_access, book_limit)
WHERE NOT EXISTS (
  SELECT 1 FROM public.library_plans WHERE library_plans.name = v.name
);

-- Final verification
SELECT 'Schema setup completed successfully!' as status;
