-- LIBRO - UNIFIED SCHEMA
-- This script creates a database structure that matches the desktop app but works with Supabase

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =================================================================
-- AUTHENTICATION & USER MANAGEMENT
-- =================================================================

-- Profiles table (linked to Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  email TEXT,
  role TEXT DEFAULT 'admin' CHECK (role IN ('admin', 'receptionist', 'librarian')),
  avatar_url TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =================================================================
-- CORE LIBRARY TABLES
-- =================================================================

-- Membership Plans (matches desktop app structure)
CREATE TABLE IF NOT EXISTS public.membership_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  duration_days INTEGER NOT NULL, -- Changed from months to days to match desktop app
  price DECIMAL(10,2) NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Members table (enhanced to match both versions)
CREATE TABLE IF NOT EXISTS public.members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  birth_date DATE,
  city TEXT,
  address TEXT,
  seat_no TEXT UNIQUE,
  library_card_no TEXT UNIQUE,
  id_document_type TEXT,
  id_number TEXT,
  photo_url TEXT,
  plan_id BIGINT REFERENCES public.membership_plans(id),
  join_date DATE DEFAULT CURRENT_DATE,
  end_date DATE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'expired', 'suspended', 'inactive')),
  qr_code TEXT,
  fingerprint_template BYTEA, -- For biometric data
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Payments table (matches desktop app)
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT REFERENCES public.members(id) ON DELETE SET NULL, -- Allow orphan payments
  amount DECIMAL(10,2) NOT NULL,
  mode TEXT DEFAULT 'cash' CHECK (mode IN ('cash', 'card', 'upi', 'bank_transfer')),
  plan_id BIGINT REFERENCES public.membership_plans(id),
  note TEXT,
  receipt_number TEXT,
  paid_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Attendance table (matches desktop app)
CREATE TABLE IF NOT EXISTS public.attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  check_in TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  check_out TIMESTAMP WITH TIME ZONE,
  source TEXT DEFAULT 'manual' CHECK (source IN ('biometric', 'manual', 'card', 'qr')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Users table for internal authentication (matches desktop app structure)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'receptionist' CHECK (role IN ('admin', 'receptionist')),
  full_name TEXT,
  email TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  last_login TIMESTAMP WITH TIME ZONE
);

-- Notifications table (matches desktop app)
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id BIGINT NOT NULL REFERENCES public.members(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('email', 'whatsapp', 'sms')),
  subject TEXT,
  message TEXT,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed')),
  sent_at TIMESTAMP WITH TIME ZONE,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Expenditures table (matches desktop app exactly)
CREATE TABLE IF NOT EXISTS public.expenditures (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  payment_mode TEXT DEFAULT 'cash' CHECK (payment_mode IN ('cash', 'card', 'upi', 'bank_transfer', 'cheque')),
  date DATE NOT NULL,
  receipt_number TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_by UUID REFERENCES public.profiles(id)
);

-- Settings table (matches desktop app)
CREATE TABLE IF NOT EXISTS public.settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT, -- Using TEXT instead of JSONB for compatibility
  description TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =================================================================
-- OPTIONAL TABLES (from desktop app)
-- =================================================================

-- Books table (if you want book management)
CREATE TABLE IF NOT EXISTS public.books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  isbn TEXT UNIQUE,
  category TEXT,
  total_copies INTEGER DEFAULT 1,
  available_copies INTEGER DEFAULT 1,
  shelf_location TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Book issues table
CREATE TABLE IF NOT EXISTS public.book_issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES public.books(id),
  member_id BIGINT REFERENCES public.members(id) ON DELETE CASCADE,
  issue_date DATE DEFAULT CURRENT_DATE,
  due_date DATE,
  return_date DATE,
  status TEXT DEFAULT 'issued' CHECK (status IN ('issued', 'returned', 'overdue')),
  fine_amount DECIMAL(10,2) DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Password change OTPs (from desktop app)
CREATE TABLE IF NOT EXISTS public.password_change_otps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  otp TEXT NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.membership_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenditures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.book_issues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_change_otps ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DO $$
DECLARE
    table_names TEXT[] := ARRAY[
        'profiles', 'membership_plans', 'members', 'payments', 'attendance', 
        'users', 'notifications', 'expenditures', 'settings', 'books', 
        'book_issues', 'password_change_otps'
    ];
    table_name TEXT;
    policy_names TEXT[] := ARRAY[
        'Enable all for authenticated',
        'Enable read access for authenticated users',
        'Enable insert access for authenticated users', 
        'Enable update access for authenticated users',
        'Enable delete access for authenticated users',
        'Public profiles are viewable by everyone',
        'Users can insert their own profile',
        'Users can update own profile'
    ];
    policy_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY table_names LOOP
        FOREACH policy_name IN ARRAY policy_names LOOP
            EXECUTE format('DROP POLICY IF EXISTS "%s" ON public.%I', policy_name, table_name);
        END LOOP;
    END LOOP;
END $$;

-- Create unified policies for all tables (allow all operations for authenticated users)
DO $$
DECLARE
    table_names TEXT[] := ARRAY[
        'membership_plans', 'members', 'payments', 'attendance', 
        'users', 'notifications', 'expenditures', 'settings', 'books', 
        'book_issues', 'password_change_otps'
    ];
    table_name TEXT;
BEGIN
    FOREACH table_name IN ARRAY table_names LOOP
        EXECUTE format('CREATE POLICY "Enable all access for authenticated users" ON public.%I FOR ALL USING (auth.role() = ''authenticated'')', table_name);
    END LOOP;
END $$;

-- Special policies for profiles table
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- =================================================================
-- FUNCTIONS & TRIGGERS
-- =================================================================

-- Handle new user signup (auto-create profile)
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, full_name, email, role, avatar_url)
  VALUES (
    NEW.id, 
    COALESCE(NEW.raw_user_meta_data->>'username', split_part(NEW.email, '@', 1)),
    NEW.raw_user_meta_data->>'full_name',
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'role', 'admin'),
    NEW.raw_user_meta_data->>'avatar_url'
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Update timestamp function
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Add update triggers where needed
DROP TRIGGER IF EXISTS handle_updated_at_profiles ON public.profiles;
CREATE TRIGGER handle_updated_at_profiles 
  BEFORE UPDATE ON public.profiles 
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at_members ON public.members;
CREATE TRIGGER handle_updated_at_members 
  BEFORE UPDATE ON public.members 
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

DROP TRIGGER IF EXISTS handle_updated_at_expenditures ON public.expenditures;
CREATE TRIGGER handle_updated_at_expenditures 
  BEFORE UPDATE ON public.expenditures 
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- =================================================================
-- SAMPLE DATA (matches desktop app defaults)
-- =================================================================

-- Insert default membership plans (converted from months to days)
INSERT INTO public.membership_plans (name, duration_days, price, description) 
SELECT * FROM (VALUES
  ('Daily', 1, 50.00, 'Daily access'),
  ('Weekly', 7, 300.00, 'Weekly access'),
  ('Monthly', 30, 1000.00, 'Monthly access'),
  ('Quarterly', 90, 2700.00, 'Quarterly access'),
  ('Half Yearly', 180, 5000.00, 'Half yearly access'),
  ('Annual', 365, 9000.00, 'Annual access'),
  ('Student Monthly', 30, 600.00, 'Student monthly plan'),
  ('Student Annual', 365, 6000.00, 'Student annual plan')
) AS v(name, duration_days, price, description)
WHERE NOT EXISTS (
  SELECT 1 FROM public.membership_plans WHERE membership_plans.name = v.name
);

-- Insert default settings (matches desktop app)
INSERT INTO public.settings (key, value, description) 
SELECT * FROM (VALUES
  ('library_name', 'Study Room Library', 'Name of the library'),
  ('library_address', 'Main Street, City', 'Library address'),
  ('library_phone', '+1234567890', 'Library contact number'),
  ('notification_days', '10', 'Days before expiry to send notifications'),
  ('auto_backup', '1', 'Enable automatic database backup'),
  ('seat_capacity', '50', 'Total reading room capacity'),
  ('operating_hours', '6:00-22:00', 'Library operating hours'),
  ('late_fee_per_day', '5.00', 'Late fee charges per day'),
  ('deposit_amount', '200.00', 'Security deposit amount')
) AS v(key, value, description)
WHERE NOT EXISTS (
  SELECT 1 FROM public.settings WHERE settings.key = v.key
);

-- Create default admin user in users table (for internal auth compatibility)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.users WHERE username = 'admin') THEN
    INSERT INTO public.users (username, password_hash, role, full_name, email) 
    VALUES (
      'admin', 
      '$2a$10$8K1p/a0dUrziV2qNlUgUyOZyUUmrGdDj8Xx.3DF1/RXrmg3HA1M1i', -- password: admin123
      'admin', 
      'System Administrator', 
      'admin@library.local'
    );
  END IF;
END $$;

-- =================================================================
-- INDEXES FOR PERFORMANCE
-- =================================================================

CREATE INDEX IF NOT EXISTS idx_members_phone ON public.members(phone);
CREATE INDEX IF NOT EXISTS idx_members_email ON public.members(email);
CREATE INDEX IF NOT EXISTS idx_members_status ON public.members(status);
CREATE INDEX IF NOT EXISTS idx_members_plan_id ON public.members(plan_id);
CREATE INDEX IF NOT EXISTS idx_members_end_date ON public.members(end_date);

CREATE INDEX IF NOT EXISTS idx_payments_member_id ON public.payments(member_id);
CREATE INDEX IF NOT EXISTS idx_payments_paid_at ON public.payments(paid_at);

CREATE INDEX IF NOT EXISTS idx_attendance_member_id ON public.attendance(member_id);
CREATE INDEX IF NOT EXISTS idx_attendance_check_in ON public.attendance(check_in);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance((check_in::DATE));

CREATE INDEX IF NOT EXISTS idx_notifications_member_id ON public.notifications(member_id);
CREATE INDEX IF NOT EXISTS idx_notifications_status ON public.notifications(status);

-- =================================================================
-- FINAL VERIFICATION
-- =================================================================

-- Show all created tables
SELECT 
  schemaname,
  tablename,
  tableowner
FROM pg_tables 
WHERE schemaname = 'public' 
  AND tablename IN (
    'profiles', 'membership_plans', 'members', 'payments', 'attendance',
    'users', 'notifications', 'expenditures', 'settings', 'books', 
    'book_issues', 'password_change_otps'
  )
ORDER BY tablename;

SELECT 'Schema setup completed successfully! Database now matches the desktop app structure.' as status;
